TodoSPA/TodoAPP/Models/Todo.cs
namespace TodoAPP.Models;

public class Todo
{
    public int Id { get; set; }
    public required string Description { get; set; }
    public bool Completed { get; set; }
}

TodoSPA/TodoAPP/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RestSharp;
using Newtonsoft.Json;
using TodoAPP.Models;
using System.Net;
using System.Reflection.Metadata.Ecma335;

namespace TodoAPP.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private IConfiguration _configuration;
    private RestClient client;
    public List<Todo> Todos;

    public IndexModel(ILogger<IndexModel> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
        client = new RestClient(_configuration.GetConnectionString("TodoAPI") ?? "");
        Todos = GetTodos();
    }

    public void OnGet()
    {

    }

    public IActionResult OnPostCompleted(int id, bool completed, string description)
    {
        UpdateTodo(id, !completed, description);
        return Page();
    }

    public IActionResult OnPostDescription(int id, bool completed, string description)
    {
        UpdateTodo(id, completed, description);
        return Page();
    }

    private void UpdateTodo(int id, bool completed, string description)
    {
        using(HttpClient httpClient = new HttpClient())
        {
            httpClient.BaseAddress = new Uri(_configuration.GetConnectionString("TodoAPI") ?? "");
            var response = httpClient.PutAsJsonAsync($"update/{id}/{completed}", description);
            if(response.Result.StatusCode == HttpStatusCode.OK) Todos = GetTodos();
        }
    }

    public IActionResult OnPostDelete(int id)
    {
        RestRequest request = new RestRequest($"delete/{id}", Method.Delete);
        var response = client.ExecuteAsync(request);
        if(response.Result.StatusCode == HttpStatusCode.OK) Todos = GetTodos();
        return Page();
    }

    public IActionResult OnPostAdd(string description)
    {
        using(HttpClient httpClient = new HttpClient())
        {
            httpClient.BaseAddress = new Uri(_configuration.GetConnectionString("TodoAPI") ?? "");
            var response = httpClient.PostAsJsonAsync("add/false", description);
            if(response.Result.StatusCode == HttpStatusCode.OK) Todos = GetTodos();
            else Console.WriteLine(response.Result.StatusCode);
        }
        return Page();
    }

    private List<Todo> GetTodos()
    {
        RestRequest request = new RestRequest("todos", Method.Get);
        var response = client.ExecuteAsync(request);
        if(response.Result.StatusCode != System.Net.HttpStatusCode.OK) return new List<Todo>();
        string? rawResult = response.Result.Content;
        List<Todo> Todos = new List<Todo>();
        if(rawResult == null || rawResult.Length  <= 2) return Todos;
        Todo? addTodo;
        while(rawResult.Length > 0) 
        {
            string[] arr = GetJsonObject(rawResult);
            string jsonObject = arr[0];
            rawResult = arr[1];
            addTodo = JsonConvert.DeserializeObject<Todo>(jsonObject);
            if(addTodo != null) 
            {
                Todos.Add(addTodo);
            }
        }
        Todos.Sort(delegate(Todo x, Todo y)
        {
            if(x.Id == y.Id) return 0;
            else if(x.Id < y.Id) return -1;
            else return 1;
        });
        return Todos;
    }

    private string[] GetJsonObject(string str)
    {
        string ans = "";
        char[] arr = str.ToCharArray();
        for(int i = 0; i < arr.Length; i++)
        {
            if(arr[i] == '\\') continue;
            ans += arr[i];
            if(arr[i] == '}') 
            {
                str = MakeSubstring(arr, i + 1);
                break;
            }
        }
        if(ans.ElementAt(0) == '"') ans = ans.Substring(1, ans.Length - 1);
        return [ans, str];
    }

    private string MakeSubstring(char[] arr, int start)
    {
        string ans = "";
        while(start < arr.Length) ans += arr[start++];
        if(ans.Length == 1) ans = "";
        return ans;
    }
}

TodoSPA/TodoAPP/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    string description = "";
}

<table class="table">

    <th></th>
    <th><h2>Todo</h2></th>
    <th></th>

    @foreach(Todo todo in Model.Todos)
    {
        <tr>
            <form asp-page-handler="completed" method="post">
                <input type="hidden" name="id" value="@todo.Id" />
                <input type="hidden" name="description" value="@todo.Description" />
                <input type="hidden" name="completed" value="@todo.Completed.ToString()" />
                @if(todo.Completed)
                {
                    <td>
                        <button class="btn btn-success">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg>
                        </button>
                    </td>
                } else {
                    <td>
                        <button class="btn btn-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect></svg>  
                        </button>
                    </td>
                }
            </form>

            <form asp-page-handler="description" method="post">
                <input type="hidden" name="id" value="@todo.Id" />
                <input type="hidden" name="completed" value="@todo.Completed.ToString()" />
                <td><input name="description" value="@todo.Description" /></td>
            </form>

            <form asp-page-handler="delete" method="post">
                <input type="hidden" name="id" value="@todo.Id" />
                <td>
                    <button class="btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                    </button>
                </td>
            </form>
        </tr>
    }
    <tr>
        <form asp-page-handler="add" method="post">
            <td>
                <button class="btn btn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3h18v18H3zM12 8v8m-4-4h8"/></svg>
                </button>
            </td>
            <td>
                <input style="color:rgba(112, 83, 124, 0.654);" name="description" value="" />
            </td>
            <td></td>
        </form>
    </tr>
</table>

TodoSPA/TodoAPP/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>